### ISSUE TITLE
Lightgun doesn't function over HDMI

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Atari7800_MiSTer#17]
I've tested all the Atari 7800 and 2600 light gun (XG-1) games using a DualSense and an 8BitDo SN3O Pro controller. I've tested using the controller detect values as "Auto" and as "Lightgun" as well as every configuration for the Cun Control and Gun Fire settings being "Joy1" "Joy2" and "Mouse" with no luck. The crosshair cursor shows up and moves. The screen flashes while shooting as well as giving you the sound of the shot, but the shot doesn't register.

Here are all the Atari 7800 and 2600 light gun games that I tested:
-Alien Brigade (7800)
-Barnyard Blaster (7800)
-Crossbow (7800)
-Meltdown (7800)
-Sentinel (7800)
-Sentinel (2600)
-Shooting Gallery (2600)

The crosshairs also don't appear with the lightgun activated on the 2600 gun games so maybe there isn't anything implemented on the 2600 side at all.

It's a shame that this doesn't work correctly because the light gun games are one of the saving graces of the 7800 library lol

Edit: Just tested 1 or 2 games for all the console cores that support light gun games, and they all seem to work with this configuration. Maybe adding an extra button like "Light Gun fire" like the NES core handles it would be a good idea? It seems to have been a good way to handle the paddle button

**Comment by iequalshane** [comment]
I found two issues in my investigation:
1) "Show Overscan" set to "Off" breaks lightgun games for the 7800 (2600 games ignore overscan settings). This is most likely due to when the lightgun sensor signal is reset based on VDE/HDE. An easy hack fix is to ignore the overscan setting when a lightgun is enabled. Otherwise, we need a different signal for resetting sensor values.
2) Lightgun aiming using a joystick wasn't centered and was so far off center for the 2600 games that it was off the screen. I've submitted a PR to fix this one at least.

**Comment by KremlingKuthroat19** [comment]
Thanks for that @iequalshane! Was just testing this core out today and almost everything works now. The only thing that's off is that Alien Brigade and Barnyard Blaster seem to have issues aiming at the screen. I can't hit anything in either game, yet every other light gun game works. Would you be willing to look into this?

**Comment by Kitrinx** [comment]
This should now be resolved with release.
